services:
  nginx:
    container_name: symfony_nginx
    image: nginx:1.30.3-alpine
    volumes:
      - ./www:/var/www:cached
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      php:
        condition: service_started
    ports:
      - "8080:80"
    networks:
      default:
        ipv4_address: ${NGINX_IP:-10.100.1.2}

  php:
    build:
      context: ./docker/php
      args:
        USER_UID: ${USER_UID:-1000}
    image: symfony_php_image
    container_name: symfony_php
    working_dir: /var/www
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_SECRET: 18ad18ee21cc27cbe29f7125ad42afe7
      DATABASE_URL: postgresql://postgres:postgres@symfony_postgresql:5432/platform?serverVersion=18&charset=utf8
      MAILER_DSN: "null://null"
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    volumes:
      - ./config/php/pool.d:/etc/php/8.3/fpm/pool.d
      - ./config/php/php-fpm.conf:/etc/php/8.3/fpm/php-fpm.conf
      - ./config/php/php.ini:/etc/php/8.3/fpm/php.ini
      - ./www:/var/www:cached
    networks:
      default:
        ipv4_address: ${PHP_IP:-10.100.1.3}

  memcached:
    container_name: symfony_memcached
    image: memcached:1.6.42-alpine
    networks:
      default:
        ipv4_address: ${MEMCACHED_IP:-10.100.1.5}

  postgresql:
    container_name: symfony_postgresql
    build: ./docker/postgres
    image: symfony_postgres_image
    volumes:
      - ./dbdata:/var/lib/postgresql:rw
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: platform
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d platform"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      default:
        ipv4_address: ${POSTGRES_IP:-10.100.1.4}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK:-10.100.1.0/24}
