version: '3.5'

services:
  nginx:
    container_name: symfony_nginx
    image: nginx:latest
    volumes:
      - ./www:/var/www:cached
      - ./var:/var/www/var
      - ./vendor:/var/www/vendor
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - postgresql
      - php
    ports:
      - "8080:80"
    networks:
      default:
        ipv4_address: ${NGINX_IP}

  php:
    build:
      context: ./docker/php
      args:
        USER_UID: ${USER_UID}
    image: symfony_php_image
    container_name: symfony_php
    depends_on:
      - postgresql
    volumes:
      - ./config/php/pool.d:/etc/php/8.1/fpm/pool.d
      - ./config/php/php-fpm.conf:/etc/php/8.1/fpm/php-fpm.conf
      - ./config/php/php.ini:/etc/php/8.1/fpm/php.ini
      - ./www:/var/www:cached
     # - ./var:/var/www/var
     # - ./vendor:/var/www/vendor
    networks:
      default:
        ipv4_address: ${PHP_IP}

  memcached:
    container_name: symfony_memcached
    image: memcached:latest
    networks:
      default:
        ipv4_address: ${MEMCACHED_IP}

  postgresql:
    container_name: symfony_postgresql
    build: ./docker/postgres
    image: postgres:13.0
    volumes:
      - ./dbdata:/var/lib/postgresql/data:rw
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: platform
    networks:
      default:
        ipv4_address: ${POSTGRES_IP}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}
