<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705102701 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE product_id_seq CASCADE');
        $this->addSql('DROP TABLE product');
        $this->addSql('ALTER TABLE articles DROP CONSTRAINT articles_author_id_fkey');
        $this->addSql('ALTER TABLE articles ALTER id TYPE INT');
        $this->addSql('ALTER TABLE articles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE articles ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE articles ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE articles ALTER created_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN articles.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN articles.author_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN articles.text IS \'\'');
        $this->addSql('COMMENT ON COLUMN articles.created_at IS \'\'');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              articles
            ADD
              CONSTRAINT FK_BFDD3168F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT comments_article_id_fkey');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT comments_author_id_fkey');
        $this->addSql('ALTER TABLE comments ALTER id TYPE INT');
        $this->addSql('ALTER TABLE comments ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE comments ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE comments ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE comments ALTER created_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN comments.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN comments.author_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN comments.comment IS \'\'');
        $this->addSql('COMMENT ON COLUMN comments.created_at IS \'\'');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              comments
            ADD
              CONSTRAINT FK_5F9E962AF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              comments
            ADD
              CONSTRAINT FK_5F9E962A7294869C FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql('ALTER TABLE users ALTER id TYPE INT');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN users.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.username IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.password_hash IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.name IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.surname IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.auth_token IS \'\'');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (
              queue_name, available_at, delivered_at,
              id
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE product_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql(<<<'SQL'
            CREATE TABLE product (
              id INT NOT NULL,
              name VARCHAR(255) NOT NULL,
              price NUMERIC(10, 2) NOT NULL,
              size INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('ALTER TABLE articles DROP CONSTRAINT FK_BFDD3168F675F31B');
        $this->addSql('ALTER TABLE articles ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE articles ALTER id SET DEFAULT nextval(\'articles_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE articles ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE articles ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE articles ALTER created_at DROP NOT NULL');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN articles.id IS 'Уникальный идентификатор статьи'
        SQL);
        $this->addSql('COMMENT ON COLUMN articles.text IS \'Текст пользователя\'');
        $this->addSql('COMMENT ON COLUMN articles.created_at IS \'Время написания статьи\'');
        $this->addSql('COMMENT ON COLUMN articles.author_id IS \'Ссылка на автора статьи\'');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              articles
            ADD
              CONSTRAINT articles_author_id_fkey FOREIGN KEY (author_id) REFERENCES users (id) ON
            UPDATE
              CASCADE ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT FK_5F9E962AF675F31B');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT FK_5F9E962A7294869C');
        $this->addSql('ALTER TABLE comments ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE comments ALTER id SET DEFAULT nextval(\'comments_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE comments ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE comments ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE comments ALTER created_at DROP NOT NULL');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN comments.id IS 'Уникальный идентификатор статьи'
        SQL);
        $this->addSql('COMMENT ON COLUMN comments.comment IS \'Текст комментария\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN comments.created_at IS 'Время написания комментария'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN comments.author_id IS 'Ссылка на комментируему статью'
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              comments
            ADD
              CONSTRAINT comments_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles (id) ON
            UPDATE
              CASCADE ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              comments
            ADD
              CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES users (id) ON
            UPDATE
              CASCADE ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              messenger_messages ALTER id
            SET
              DEFAULT nextval(
                'messenger_messages_id_seq' :: regclass
              )
        SQL);
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('ALTER TABLE users ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN users.id IS 'Уникальный идентификатор пользователя'
        SQL);
        $this->addSql('COMMENT ON COLUMN users.username IS \'Уникальное имя пользователя\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN users.password_hash IS 'Зашифрованный пароль пользователя'
        SQL);
        $this->addSql('COMMENT ON COLUMN users.name IS \'Имя пользователя\'');
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN users.surname IS 'Дополнительное имя (фамилия) пользователя'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN users.auth_token IS 'Токен пользователя для входа в систему (из куки-файла)'
        SQL);
    }
}
