<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260705133000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add article likes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE article_likes (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              article_id INT NOT NULL,
              user_id INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX article_likes_article_user_key ON article_likes (article_id, user_id)');
        $this->addSql('CREATE INDEX IDX_3E7D3C6C7294869C ON article_likes (article_id)');
        $this->addSql('CREATE INDEX IDX_3E7D3C6CA76ED395 ON article_likes (user_id)');
        $this->addSql('ALTER TABLE article_likes ADD CONSTRAINT FK_4B73C82E7294869C FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_likes ADD CONSTRAINT FK_4B73C82EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE article_likes DROP CONSTRAINT FK_4B73C82E7294869C');
        $this->addSql('ALTER TABLE article_likes DROP CONSTRAINT FK_4B73C82EA76ED395');
        $this->addSql('DROP TABLE article_likes');
    }
}
